dist: xenial

language: python

python:
  - 3.6
  - 3.7

install:
    - mkdir -p $HOME/bin
    - pushd $HOME/bin
    - curl -o nvim -L https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    - chmod u+x nvim
    - pip install pynvim
    - curl -o rclone.zip https://downloads.rclone.org/rclone-current-linux-amd64.zip
    - unzip rclone.zip
    - mv rclone-*/rclone .
    - popd


script:
    - PATH="$HOME/bin:$PATH"
    - cd test
    - python test.py
