sudo: true
dist: trusty

language: python

python:
    - 3.3
    - 3.4
    - 3.5

install:
    - export NVIMDIR=$HOME/neovim/bin
    - mkdir -p $NVIMDIR
    - curl -o $NVIMDIR/nvim -L https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    - chmod u+x $NVIMDIR/nvim
    - pip install neovim
    - pip install flake8

script:
    - PATH="$NVIMDIR:$PATH"
    - cd test
    - bash test.sh
    - py.test --flake8 .
